### ISSUE TITLE
Checker test.grammar diagnostic is absolute-path sensitive

### ISSUE THREAD

**Issue by BurtHarris** [rbuckton/grammarkdown#22]
After cloning and running `npm install`, I got an immediate test failure.   

Root cause appears to be the absolute path names in the baseline files named `test.grammar.diagnostics`.   The contents of this file used in a test depends on the root directory where the project is cloned.   It seems like this should be processed to remove the root directory prefix before comparing the local baseline against the reference baseline.

The verbatim test output:   

```

[12:44:30] Starting 'test:lib'...
  ................................

  31 passing (766ms)
  1 failing

  1) Checker test.grammar diagnostics:
     Error: The baseline file 'test.grammar.diagnostics' has changed.
      at Object.compareBaseline (C:\code\grammarkdown\src\tests\diff.ts:140:15)
      at Context.<anonymous> (C:\code\grammarkdown\src\tests\checker-tests.ts:32:13)
      at callFn (C:\code\grammarkdown\node_modules\mocha\lib\runnable.js:326:21)
      at Test.Runnable.run (C:\code\grammarkdown\node_modules\mocha\lib\runnable.js:319:7)
      at Runner.runTest (C:\code\grammarkdown\node_modules\mocha\lib\runner.js:422:10)
      at C:\code\grammarkdown\node_modules\mocha\lib\runner.js:528:12
      at next (C:\code\grammarkdown\node_modules\mocha\lib\runner.js:342:14)
      at C:\code\grammarkdown\node_modules\mocha\lib\runner.js:352:7
      at next (C:\code\grammarkdown\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\code\grammarkdown\node_modules\mocha\lib\runner.js:320:5)

[12:44:30] 'test:lib' errored after 865 ms
[12:44:30] Error in plugin 'gulp-mocha'
```

**Comment by rbuckton** [comment]
This looks to have been resolved by a different change.
